# Generated by Django 3.1.12 on 2023-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0002_body_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(default='tittle', max_length=250)),
                ('Text', models.TextField(default='text')),
                ('Image', models.CharField(default='image', max_length=2500)),
            ],
        ),
    ]
