# Generated by Django 3.1.12 on 2023-04-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0004_nearby_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrontDesk', models.BooleanField(default='false')),
                ('Wifi', models.BooleanField(default='false')),
                ('Board', models.BooleanField(default='false')),
                ('Rooftop_Cafe', models.BooleanField(default='false')),
                ('Health_Club', models.BooleanField(default='false')),
                ('Express_checks', models.BooleanField(default='false')),
                ('Wave_Bar', models.BooleanField(default='false')),
                ('Conference_Hall', models.BooleanField(default='false')),
                ('Alchemy', models.BooleanField(default='false')),
                ('Suncafe', models.BooleanField(default='false')),
                ('Doctor', models.BooleanField(default='false')),
                ('Spa', models.BooleanField(default='false')),
                ('Babysitting', models.BooleanField(default='false')),
                ('Electricity', models.BooleanField(default='false')),
                ('Concierge', models.BooleanField(default='false')),
                ('Conditinoer', models.BooleanField(default='false')),
                ('Security', models.BooleanField(default='false')),
                ('TravelTour', models.BooleanField(default='false')),
                ('Currency_Exchange', models.BooleanField(default='false')),
                ('Laundry', models.BooleanField(default='false')),
                ('Casino', models.BooleanField(default='false')),
                ('Parking', models.BooleanField(default='false')),
                ('Elevator', models.BooleanField(default='false')),
                ('Jacuzzi', models.BooleanField(default='false')),
                ('Room_Service', models.BooleanField(default='false')),
                ('Accept_Cards', models.BooleanField(default='false')),
            ],
        ),
    ]
