# Generated by Django 3.1.12 on 2023-04-03 12:11

import Ttrail.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0006_auto_20230403_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequiredLanding', models.BooleanField(default=False)),
                ('Text', models.CharField(default='banner', max_length=25000000)),
                ('Room', djongo.models.fields.ArrayField(default=[], model_container=Ttrail.models.Room_Detail)),
            ],
        ),
    ]
