# Generated by Django 3.1.12 on 2023-04-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0007_hotel_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_date', models.CharField(default='Since', max_length=20)),
                ('Address', models.CharField(default='Address', max_length=20)),
                ('State', models.CharField(default='State Name', max_length=20)),
                ('City', models.CharField(default='City Name', max_length=20)),
                ('Newslette', models.BooleanField(default='Newsletter', max_length=20)),
                ('Logo', models.CharField(default='logo', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.BooleanField(default=False)),
                ('Instagram', models.BooleanField(default=False)),
                ('Linkedin', models.BooleanField(default=False)),
                ('Tripadvisor', models.BooleanField(default=False)),
                ('Twitter', models.BooleanField(default=False)),
            ],
        ),
    ]
