# Generated by Django 3.1.12 on 2023-04-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0008_footer_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='Newslette',
        ),
        migrations.AddField(
            model_name='footer',
            name='Newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
