# Generated by Django 3.1.12 on 2023-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0009_auto_20230404_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='Email',
            field=models.CharField(default='email', max_length=2000),
        ),
    ]
