# Generated by Django 3.1.12 on 2023-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0010_footer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_links',
            name='Facebook',
            field=models.CharField(default='facebook', max_length=2000),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='Instagram',
            field=models.CharField(default='tlnstagram', max_length=2000),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='Linkedin',
            field=models.CharField(default='linkedin', max_length=2000),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='Tripadvisor',
            field=models.CharField(default='tripadvisor', max_length=2000),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='Twitter',
            field=models.CharField(default='twitter', max_length=2000),
        ),
    ]
