# Generated by Django 3.1.12 on 2023-04-19 11:02

import Ttrail.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0014_popups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popups',
            name='Ads',
            field=djongo.models.fields.ArrayField(default=[], model_container=Ttrail.models.advertisement),
        ),
    ]
