# Generated by Django 3.1.12 on 2023-05-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0015_auto_20230419_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='body_image',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel_rooms',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='nearby_places',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='popups',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='services',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
        migrations.AddField(
            model_name='social_links',
            name='Domain',
            field=models.CharField(default='Domain', max_length=100),
        ),
    ]
