# Generated by Django 3.1.12 on 2023-05-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttrail', '0017_auto_20230501_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Engine_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(default='Domain', max_length=100)),
                ('EngineLink', models.CharField(default='Domain', max_length=1000)),
            ],
        ),
    ]
